api = "0.7"

[buildpack]
  homepage = "https://github.com/initializ-buildpacks/nodejs"
  id = "initializ-buildpacks/nodejs"
  name = "Initializ Buildpack for Node.js"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/initializ-buildpacks/nodejs/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/ca-certificates"
    optional = true
    version = "4.0.4"

  [[order.group]]
    id = "initializ-buildpacks/watchexec"
    optional = true
    version = "2.8.15"

  [[order.group]]
    id = "initializ-buildpacks/node-engine"
    version = "3.6.8"

  [[order.group]]
    id = "initializ-buildpacks/yarn"
    version = "1.2.10"

  [[order.group]]
    id = "initializ-buildpacks/yarn-install"
    version = "1.2.12"

  [[order.group]]
    id = "initializ-buildpacks/node-run-script"
    optional = true
    version = "1.0.24"

  [[order.group]]
    id = "initializ-buildpacks/node-start"
    optional = true
    version = "1.1.16"

  [[order.group]]
    id = "initializ-buildpacks/yarn-start"
    optional = true
    version = "1.1.11"

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    optional = true
    version = "5.6.21"

  [[order.group]]
    id = "initializ-buildpacks/datadog"
    optional = true
    version = "4.8.13"

  [[order.group]]
    id = "initializ-buildpacks/environment-variables"
    optional = true
    version = "4.5.14"

  [[order.group]]
    id = "initializ-buildpacks/image-labels"
    optional = true
    version = "4.6.3"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/ca-certificates"
    optional = true
    version = "4.0.4"

  [[order.group]]
    id = "initializ-buildpacks/watchexec"
    optional = true
    version = "2.8.15"

  [[order.group]]
    id = "initializ-buildpacks/node-engine"
    version = "3.6.8"

  [[order.group]]
    id = "initializ-buildpacks/npm-install"
    version = "1.3.12"

  [[order.group]]
    id = "initializ-buildpacks/node-run-script"
    optional = true
    version = "1.0.24"

  [[order.group]]
    id = "initializ-buildpacks/node-start"
    optional = true
    version = "1.1.16"

  [[order.group]]
    id = "initializ-buildpacks/npm-start"
    optional = true
    version = "1.4.2"

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    optional = true
    version = "5.6.21"

  [[order.group]]
    id = "initializ-buildpacks/datadog"
    optional = true
    version = "4.8.13"

  [[order.group]]
    id = "initializ-buildpacks/environment-variables"
    optional = true
    version = "4.5.14"

  [[order.group]]
    id = "initializ-buildpacks/image-labels"
    optional = true
    version = "4.6.3"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/ca-certificates"
    optional = true
    version = "4.0.4"

  [[order.group]]
    id = "initializ-buildpacks/watchexec"
    optional = true
    version = "2.8.15"

  [[order.group]]
    id = "initializ-buildpacks/node-engine"
    version = "3.6.8"

  [[order.group]]
    id = "initializ-buildpacks/node-start"
    version = "1.1.16"

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    optional = true
    version = "5.6.21"

  [[order.group]]
    id = "initializ-buildpacks/datadog"
    optional = true
    version = "4.8.13"

  [[order.group]]
    id = "initializ-buildpacks/environment-variables"
    optional = true
    version = "4.5.14"

  [[order.group]]
    id = "initializ-buildpacks/image-labels"
    optional = true
    version = "4.6.3"
