api = "0.7"

[buildpack]
  homepage = "https://github.com/initializ-buildpacks/nodejs"
  id = "initializ-buildpacks/nodejs"
  name = "Initializ Buildpack for Node.js"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/initializ-buildpacks/nodejs/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.6"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.8.6"

  [[order.group]]
    id = "initializ-buildpacks/node-engine"
    version = "3.0.2"

  [[order.group]]
    id = "initializ-buildpacks/yarn"
    version = "1.2.0"

  [[order.group]]
    id = "initializ-buildpacks/yarn-install"
    version = "1.2.2"

  [[order.group]]
    id = "initializ-buildpacks/node-run-script"
    optional = true
    version = "1.0.14"

  [[order.group]]
    id = "initializ-buildpacks/node-start"
    optional = true
    version = "1.1.3"

  [[order.group]]
    id = "initializ-buildpacks/yarn-start"
    optional = true
    version = "1.1.3"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.7"

  [[order.group]]
    id = "paketo-buildpacks/datadog"
    optional = true
    version = "3.6.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.6"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.5"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.6"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.8.6"

  [[order.group]]
    id = "initializ-buildpacks/node-engine"
    version = "3.0.2"

  [[order.group]]
    id = "initializ-buildpacks/npm-install"
    version = "1.3.1"

  [[order.group]]
    id = "initializ-buildpacks/node-run-script"
    optional = true
    version = "1.0.14"

  [[order.group]]
    id = "initializ-buildpacks/node-start"
    optional = true
    version = "1.1.3"

  [[order.group]]
    id = "initializ-buildpacks/npm-start"
    optional = true
    version = "1.0.15"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.7"

  [[order.group]]
    id = "paketo-buildpacks/datadog"
    optional = true
    version = "3.6.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.6"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.5"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.6"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.8.6"

  [[order.group]]
    id = "initializ-buildpacks/node-engine"
    version = "3.0.2"

  [[order.group]]
    id = "initializ-buildpacks/node-start"
    version = "1.1.3"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.7"

  [[order.group]]
    id = "paketo-buildpacks/datadog"
    optional = true
    version = "3.6.0"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.6"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.5"
